---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets


- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    tempmin: 0
    tempmax: 100
    units: metric
    refresh: 3000
    diskUnits: bytes


- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true

- openmeteo:
    label: Bokaro
    latitude: 23.669296
    longitude: 86.15
    timezone: Asia/Kolkata
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1

- search:
    provider: google
    target: _

- widget:
   type: adguard
   url: http://172.31.0.182:85/
   username: utkarsh
   password: utkarsh1850
